# Generated by Django 5.x for mascotas app schema updates.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='ip_origen',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad',
            field=models.PositiveIntegerField(blank=True, help_text='Edad aproximada en años, si se conoce', null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='ip_origen',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tamano',
            field=models.CharField(blank=True, choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tipo_animal',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('roedor', 'Roedor'), ('reptil', 'Reptil'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
